{% set name = "pysjef" %}
{% set version = "1.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/molpro/sjef/archive/refs/tags//{{ version }}.tar.gz
  sha256: 52fbde358acba17d70c4fa2828610352aa4ca05d22a344e167dfc614928d6f18

build:
  skip: True  # [win]
  script:
    - echo __version__ = \"{{ version }}\" > pysjef/pysjef/_version.py  # [unix]
    - cmake -B cmake-build . -DCMAKE_INSTALL_PREFIX=$PREFIX  # [linux]
    - CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY -DBOOST_ASIO_DISABLE_STD_ALIGNED_ALLOC" cmake -B cmake-build . -DCMAKE_INSTALL_PREFIX=$PREFIX  # [osx and x86]
    - cmake -B cmake-build . -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$PREFIX  # [arm64]
    - cmake --build cmake-build -t install  # [unix]
    - ctest -j 1 --test-dir cmake-build -E 'Shell.remote.*|test-Command' || ctest -VV -j 1 --test-dir cmake-build -E 'Shell.remote.*|test-Command'  # [x86]
    - cd pysjef && {{ PYTHON }} -m pip install . -vv  # [unix]
    - rm -f $(grep -v /bin/sjef ../cmake-build/install_manifest.txt)  # [unix] 
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.14
    - make
  host:
    - python
    - pip
    - boost-cpp
    - pugixml >=1.10
    - cython >=0.24
  run:
    - python
    - boost-cpp
    - lxml >=4.0
    - rsync
    - regex
    - numpy

test:
  imports:
    - pysjef
    - pysjef.project
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/molpro/sjef
  summary: |
        Python Simple Job Execution Framework (Pysjef) is pronounced pie-chef
  description: A library that supports the running of any program asynchronously either locally, directly on a remote machine, or via a batch queueing system
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://molpro.gitlab.io/pysjef
  dev_url: https://github.com/molpro/sjef

extra:
  recipe-maintainers:
    - molpro-owner
    - nick-wilson
